FROM alpine:3

LABEL author="Alpian Roymundus Siringo-ringo"
LABEL company="PT. Keren Banget" website="https://instagram.com/roymunduss_"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"
